version: "3"
services:
  mongodb:
    container_name: ortoo_mongodb_testing
    image: mongo:latest
    volumes:
      - ./docker_volumes/mongodb:/data
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ortoo-test

  mongo-express:
    container_name: ortoo_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ortoo-test
    depends_on:
      - mongodb
  mqtt-mosquitto:
    container_name: mqtt-mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./docker_volumes/mosquitto:/mosquitto
      - ./config:/mosquitto/config