version: "3.4"
services:
  orda-mongodb:
    container_name: orda-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-db:/data/db
    ports:
      - 0.0.0.0:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: orda-test

  orda-emqx:
    container_name: orda-emqx
    image: emqx/emqx:latest
    restart: always
    ports:
      - 0.0.0.0:18181:1883  # port for MQTT
      - 0.0.0.0:18881:8083  # for WebSocket/HTTP
      - 0.0.0.0:18081:18083  # for dashboard
    #      - "8883"  # port for MQTT(SSL)
    #      - "8084"  # for WSS / HTTPS
    #      - "11883" # port for internal MQTT/TCP
    #      - "4369"  # for port mapping (epmd)
    #      - "4370"  # for port mapping
    #      - "5369"  # for gen_rpc port mapping
    #      - "6369"  # for distributed node
    #      - "8081"  # for mgmt API
    environment:
      EMQX_NAME: orda-emqx
      EMQX_HOST: 0.0.0.0
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
      EMQX_LOG__LEVEL: "debug"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log

  orda-server:
    container_name: orda-server
    image: orda-io/orda:${VERSION}
    restart: always
    command: sh -c "sleep 5 && /app/orda_server --conf /config/docker-config.json"
    ports:
      - 0.0.0.0:19061:19061  # for port gRPC protocol
      - 0.0.0.0:19861:19861  # for port HTTP control
    volumes:
      - type: bind
        source: ./config/docker-config.json
        target: /config/docker-config.json
        read_only: true
    depends_on:
      - orda-mongodb
      - orda-emqx

volumes:
  mongodb-configdb: { }
  mongodb-db: { }
  emqx-data: { }
  emqx-etc: { }
  emqx-log: { }

