version: "3.4"
services:
  ortoo-mongodb:
    container_name: ortoo-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ortoo-test

  ortoo-emqx:
    container_name: ortoo-emqx
    image: emqx/emqx:latest
    restart: always
    ports:
      - 18181:1883  # port for MQTT
      - 18881:8083  # for WebSocket/HTTP
      - 18081:18083  # for dashboard
    #      - "8883"  # port for MQTT(SSL)
    #      - "8084"  # for WSS / HTTPS
    #      - "11883" # port for internal MQTT/TCP
    #      - "4369"  # for port mapping (epmd)
    #      - "4370"  # for port mapping
    #      - "5369"  # for gen_rpc port mapping
    #      - "6369"  # for distributed node
    #      - "8081"  # for mgmt API
    environment:
      EMQX_NAME: ortoo-emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
      EMQX_LOG__LEVEL: "debug"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log

  ortoo-server:
    container_name: ortoo-server
    image: knowhunger/ortoo:0.0.1
    restart: always
    command: sh -c "sleep 5 && /app/ortoo_server --conf /config/local-config.json"
    ports:
      - 19061:19061  # for port gRPC protocol
      - 19861:19861  # for port HTTP control
    volumes:
      - type: bind
        source: ./config/local-config.json
        target: /config/local-config.json
        read_only: true
    depends_on:
      - ortoo-mongodb
      - ortoo-emqx

  ortoo-envoy-grpc-proxy:
    container_name: ortoo-envoy-grpc-proxy
    image: envoyproxy/envoy:v1.16-latest
    restart: always
    command: envoy -c /config/envoy.yaml
    ports:
      - 29065:29065
    volumes:
      - type: bind
        source: ./config/envoy.yaml
        target: /config/envoy.yaml
        read_only: true
    depends_on:
      - ortoo-server

volumes:
  mongodb-configdb: { }
  mongodb-db: { }
  emqx-data: { }
  emqx-etc: { }
  emqx-log: { }

