version: "3.4"
services:
  mongodb:
    container_name: ortoo_mongodb_testing
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_configdb:/data/configdb
      - mongodb_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ortoo-test

  mongo-express:
    container_name: ortoo_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ortoo-test
    depends_on:
      - mongodb
  mqtt-mosquitto:
    container_name: mqtt-mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 11883:11883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./config:/mosquitto/config
volumes:
  mongodb_configdb: { }
  mongodb_db: { }
  mosquitto_data: { }
  mosquitto_log: { }
