version: "3"
services:
  mongodb:
    container_name: ortoo_mongodb_testing
    image: mongo:4.2.0-bionic
    volumes:
      - ./docker:/data
      - mongodb_volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ortoo-test

  mongo-express:
    container_name: ortoo_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 18082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ortoo-test
    depends_on:
      - mongodb
volumes:
  mongodb_volume:
